// Code generated by "stringer -type=IndexType -output=index_type_string_gen.go"; DO NOT EDIT.

package schemalex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IndexTypeNone-0]
	_ = x[IndexTypeBtree-1]
	_ = x[IndexTypeHash-2]
}

const _IndexType_name = "IndexTypeNoneIndexTypeBtreeIndexTypeHash"

var _IndexType_index = [...]uint8{0, 13, 27, 40}

func (i IndexType) String() string {
	if i < 0 || i >= IndexType(len(_IndexType_index)-1) {
		return "IndexType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IndexType_name[_IndexType_index[i]:_IndexType_index[i+1]]
}
