// Code generated by "stringer -type=ReferenceOption -output=reference_option_string_gen.go"; DO NOT EDIT.

package schemalex

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReferenceOptionNone-0]
	_ = x[ReferenceOptionRestrict-1]
	_ = x[ReferenceOptionCascade-2]
	_ = x[ReferenceOptionSetNull-3]
	_ = x[ReferenceOptionNoAction-4]
}

const _ReferenceOption_name = "ReferenceOptionNoneReferenceOptionRestrictReferenceOptionCascadeReferenceOptionSetNullReferenceOptionNoAction"

var _ReferenceOption_index = [...]uint8{0, 19, 42, 64, 86, 109}

func (i ReferenceOption) String() string {
	if i < 0 || i >= ReferenceOption(len(_ReferenceOption_index)-1) {
		return "ReferenceOption(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReferenceOption_name[_ReferenceOption_index[i]:_ReferenceOption_index[i+1]]
}
