name: goreleaser

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"

      - name: Configure AWS Credentials
        uses: fuller-inc/actions-aws-assume-role@db10fc9ddce76ac14ce9182c2433f497580bec93 # v1.9.2
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::445285296882:role/rpm-repository-users-SchemalexDeployRole-1HXKOEZ82HCRH
          role-session-tagging: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6 # v4.2.2
        with:
          subject-path: |
            dist/*.tar.gz
            dist/*.zip
            dist/*.txt
            dist/*.apk
            dist/*.deb
            dist/*.rpm
